install.packages(c('knitr', 'pheatmap', 'tidyverse', 'hexbin', 'doParallel', 'ggplot2', 'ggbeeswarm', 'ggrepel', 'import', 'logging', 'amap',
'grid', 'gridExtra', 'gtable', 'futile.logger', 'labeling','snow'), dependencies = TRUE)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
BiocManager::install("tximeta")
BiocManager::install("devtools")
BiocManager::install("SummarizedExperiment")
BiocManager::install("vsn")
BiocManager::install("ggalt")
BiocManager::install("ggrastr")
BiocManager::install("EnhancedVolcano")
BiocManager::install("edgeR")
BiocManager::install("limma")
BiocManager::install("EBSeq")
BiocManager::install("biomaRt")
BiocManager::install("VennDiagram")
BiocManager::install("RColorBrewer")
BiocManager::install("NOISeq")
BiocManager::install("baySeq")

